### ISSUE TITLE
When the url is not a feed

### ISSUE THREAD

**Issue by fernand0** [m3nu/upodder#11]
Hello,

somtimes a podcast disappears. But the url still works and upodder downloads it, tryies to parse it and fails:

`Traceback (most recent call last):
  File "/home/user/.pyenv/versions/2.7.10/bin/upodder", line 11, in <module>
    sys.exit(main())
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/site-packages/upodder/upodder.py", line 193, in main
    process_feed(url)
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/site-packages/upodder/upodder.py", line 168, in process_feed
    l.info("Checking feed: %s"%feed.feed.title)
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/site-packages/feedparser.py", line 400, in __getattr__
    raise AttributeError, "object has no attribute '%s'" % key
AttributeError: object has no attribute 'title'
`
That is, it looks for some attribute and it does not exit.
As a suggestion, at least upodder should show which feed is parsing in order to make easier to delete it. Something like this:

`        if url and url[0] not in CONFIGCOMMENT:
            l.debug("Url: %s" % url)
            process_feed(url)
`
It would be nice to be able to capture the exception and to allow upodder to continue downloading podcasts...

Thank you and keep up the good work!

**Comment by m3nu** [comment]
Thanks for the valuable suggestion. That's a good idea. I'll implement it when going over the code the next time.

**Comment by m3nu** [comment]
Fixed in e0ddee72
