### ISSUE TITLE
I continually get this error, which I just ignore

### ISSUE THREAD

**Issue by Jadamso** [m3nu/upodder#21]
Too old for us: Celebrating (or not) the Centenary of the Russian Revolution [Audio]
Already seen: Celebrity [Audio]
Downloading The French Election and the Left [Audio] from http://media.rawvoice.com/lse_publiclecturesandevents/richmedia.lse.ac.uk/publiclecturesandevents/20170509_1830_theFrenchElectionAndTheLeft.mp3
100%|████████████████████████████████████████████████| 42.5M/42.5M [00:25<00:00, 1.66MB/s]
Moving {/tmp/upodder/cadce213ff5c92391888d1e784a4180c93cad59d} to {/home/Jadamso/Desktop/MiscPersonal/Audio/Podx/The_French_Election_and_the_Left_Audio_.mp3}
Traceback (most recent call last):
  File "/usr/bin/upodder", line 9, in <module>
    load_entry_point('upodder==0.6.9', 'console_scripts', 'upodder')()
  File "/usr/lib/python2.7/site-packages/upodder/upodder.py", line 212, in main
    process_feed(url)
  File "/usr/lib/python2.7/site-packages/upodder/upodder.py", line 192, in process_feed
    EntryProcessor(entry, feed)
  File "/usr/lib/python2.7/site-packages/upodder/upodder.py", line 98, in __init__
    SeenEntry( pub_date=self.pub_date, hashed=self.hashed)
  File "/usr/lib64/python2.7/site-packages/sqlobject/main.py", line 1301, in __init__
    self._create(id, **kw)
  File "/usr/lib64/python2.7/site-packages/sqlobject/main.py", line 1352, in _create
    self._SO_finishCreate(id)
  File "/usr/lib64/python2.7/site-packages/sqlobject/main.py", line 1381, in _SO_finishCreate
    self._init(id)
  File "/usr/lib64/python2.7/site-packages/sqlobject/main.py", line 986, in _init
    self._SO_selectInit(selectResults)
  File "/usr/lib64/python2.7/site-packages/sqlobject/main.py", line 1227, in _SO_selectInit
    colValue = _col.to_python(colValue, self._SO_validatorState)
  File "/usr/lib64/python2.7/site-packages/sqlobject/col.py", line 1251, in to_python
    return datetime.timedelta(seconds=value.seconds)
AttributeError: 'str' object has no attribute 'seconds'

[podx.txt](https://github.com/m3nu/upodder/files/1001836/podx.txt)

**Comment by m3nu** [comment]
Hi @Jadamso , thanks for writing in. The bug you encounter seems to be located deep inside [sqlobject](http://www.sqlobject.org/). Did you try updating that package? Which version are you using, when running `pip freeze`?

**Comment by Jadamso** [comment]
None. It was not installed. I apologize for my laziness in debugging. My
script works now.

Jordan Adamson, Ph.D. Economics
https://sites.google.com/a/g.clemson.edu/ja-resources/
*``The good of other times let people state; I think it lucky I was born so
late" - Ovid*

**Comment by m3nu** [comment]
Thanks for checking. Closing this issue.
